export default {
  login: "kotobuki562",
  id: 67810971,
  node_id: "MDQ6VXNlcjY3ODEwOTcx",
  avatar_url: "https://avatars.githubusercontent.com/u/67810971?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/kotobuki562",
  html_url: "https://github.com/kotobuki562",
  followers_url: "https://api.github.com/users/kotobuki562/followers",
  following_url:
    "https://api.github.com/users/kotobuki562/following{/other_user}",
  gists_url: "https://api.github.com/users/kotobuki562/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/kotobuki562/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/kotobuki562/subscriptions",
  organizations_url: "https://api.github.com/users/kotobuki562/orgs",
  repos_url: "https://api.github.com/users/kotobuki562/repos",
  events_url: "https://api.github.com/users/kotobuki562/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/kotobuki562/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "https://qiita.com/kotobuki562",
  location: null,
  email: null,
  hireable: null,
  bio: "やあ。\r\n自称React/NextDevelopperです。",
  twitter_username: "NEKO_and_SPA",
  public_repos: 34,
  public_gists: 0,
  followers: 7,
  following: 13,
  created_at: "2020-07-04T00:39:46Z",
  updated_at: "2021-01-14T10:03:36Z",
};
