export default [
  {
    login: "omochi1224",
    id: 18626645,
    node_id: "MDQ6VXNlcjE4NjI2NjQ1",
    avatar_url: "https://avatars.githubusercontent.com/u/18626645?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/omochi1224",
    html_url: "https://github.com/omochi1224",
    followers_url: "https://api.github.com/users/omochi1224/followers",
    following_url:
      "https://api.github.com/users/omochi1224/following{/other_user}",
    gists_url: "https://api.github.com/users/omochi1224/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/omochi1224/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/omochi1224/subscriptions",
    organizations_url: "https://api.github.com/users/omochi1224/orgs",
    repos_url: "https://api.github.com/users/omochi1224/repos",
    events_url: "https://api.github.com/users/omochi1224/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/omochi1224/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "airiclover",
    id: 69450341,
    node_id: "MDQ6VXNlcjY5NDUwMzQx",
    avatar_url: "https://avatars.githubusercontent.com/u/69450341?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/airiclover",
    html_url: "https://github.com/airiclover",
    followers_url: "https://api.github.com/users/airiclover/followers",
    following_url:
      "https://api.github.com/users/airiclover/following{/other_user}",
    gists_url: "https://api.github.com/users/airiclover/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/airiclover/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/airiclover/subscriptions",
    organizations_url: "https://api.github.com/users/airiclover/orgs",
    repos_url: "https://api.github.com/users/airiclover/repos",
    events_url: "https://api.github.com/users/airiclover/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/airiclover/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "y-arimura1222",
    id: 59641667,
    node_id: "MDQ6VXNlcjU5NjQxNjY3",
    avatar_url: "https://avatars.githubusercontent.com/u/59641667?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/y-arimura1222",
    html_url: "https://github.com/y-arimura1222",
    followers_url: "https://api.github.com/users/y-arimura1222/followers",
    following_url:
      "https://api.github.com/users/y-arimura1222/following{/other_user}",
    gists_url: "https://api.github.com/users/y-arimura1222/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/y-arimura1222/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/y-arimura1222/subscriptions",
    organizations_url: "https://api.github.com/users/y-arimura1222/orgs",
    repos_url: "https://api.github.com/users/y-arimura1222/repos",
    events_url: "https://api.github.com/users/y-arimura1222/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/y-arimura1222/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gabriel6181997",
    id: 70248190,
    node_id: "MDQ6VXNlcjcwMjQ4MTkw",
    avatar_url: "https://avatars.githubusercontent.com/u/70248190?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gabriel6181997",
    html_url: "https://github.com/gabriel6181997",
    followers_url: "https://api.github.com/users/gabriel6181997/followers",
    following_url:
      "https://api.github.com/users/gabriel6181997/following{/other_user}",
    gists_url: "https://api.github.com/users/gabriel6181997/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gabriel6181997/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/gabriel6181997/subscriptions",
    organizations_url: "https://api.github.com/users/gabriel6181997/orgs",
    repos_url: "https://api.github.com/users/gabriel6181997/repos",
    events_url: "https://api.github.com/users/gabriel6181997/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gabriel6181997/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Connie0914",
    id: 71988605,
    node_id: "MDQ6VXNlcjcxOTg4NjA1",
    avatar_url: "https://avatars.githubusercontent.com/u/71988605?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Connie0914",
    html_url: "https://github.com/Connie0914",
    followers_url: "https://api.github.com/users/Connie0914/followers",
    following_url:
      "https://api.github.com/users/Connie0914/following{/other_user}",
    gists_url: "https://api.github.com/users/Connie0914/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Connie0914/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Connie0914/subscriptions",
    organizations_url: "https://api.github.com/users/Connie0914/orgs",
    repos_url: "https://api.github.com/users/Connie0914/repos",
    events_url: "https://api.github.com/users/Connie0914/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Connie0914/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ken505",
    id: 68226398,
    node_id: "MDQ6VXNlcjY4MjI2Mzk4",
    avatar_url: "https://avatars.githubusercontent.com/u/68226398?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ken505",
    html_url: "https://github.com/ken505",
    followers_url: "https://api.github.com/users/ken505/followers",
    following_url: "https://api.github.com/users/ken505/following{/other_user}",
    gists_url: "https://api.github.com/users/ken505/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ken505/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ken505/subscriptions",
    organizations_url: "https://api.github.com/users/ken505/orgs",
    repos_url: "https://api.github.com/users/ken505/repos",
    events_url: "https://api.github.com/users/ken505/events{/privacy}",
    received_events_url: "https://api.github.com/users/ken505/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ryuji-ito-0222",
    id: 66236149,
    node_id: "MDQ6VXNlcjY2MjM2MTQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/66236149?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ryuji-ito-0222",
    html_url: "https://github.com/ryuji-ito-0222",
    followers_url: "https://api.github.com/users/ryuji-ito-0222/followers",
    following_url:
      "https://api.github.com/users/ryuji-ito-0222/following{/other_user}",
    gists_url: "https://api.github.com/users/ryuji-ito-0222/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ryuji-ito-0222/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ryuji-ito-0222/subscriptions",
    organizations_url: "https://api.github.com/users/ryuji-ito-0222/orgs",
    repos_url: "https://api.github.com/users/ryuji-ito-0222/repos",
    events_url: "https://api.github.com/users/ryuji-ito-0222/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ryuji-ito-0222/received_events",
    type: "User",
    site_admin: false,
  },
];
